# NAME: Derek Vance
# EMAIL: dvance@g.ucla.edu
# ID: 604970765

TAR_NAME = lab4a-604970765.tar.gz
FILES_TO_TAR = my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

dist:
	tar -czf $(TAR_NAME) $(FILES_TO_TAR)